package fr.univrouen.stb23v1.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

/**
 * An STB client.
 */
@Entity
@Table(name = "client")
@XmlAccessorType(XmlAccessType.FIELD)
public class Client {

    /**
     * Autogenerated id.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlTransient
    private Integer id;

    /**
     * The client Person type.
     */
    @XmlElement
    @OneToOne(cascade=CascadeType.ALL)
    @JoinColumn(name = "personId")
    private Person person;

    /**
     * The client entity name.
     */
    @XmlElement
    private String entity;

    /**
     * The client emails address list.
     */
    @XmlElement(name = "mail")
    private List<String> mails = new ArrayList<>();

    /**
     * The client phone numbers list.
     */
    @XmlElement(name = "tel")
    private List<String> phoneNumbers = new ArrayList<>();

    public Client() {
    }

    public Integer getId() {
        return id;
    }

    public Person getPerson() {
        return person;
    }

    public String getEntity() {
        return entity;
    }

    public List<String> getMails() {
        return mails;
    }

    public List<String> getPhoneNumbers() {
        return phoneNumbers;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public void setEntity(String entity) {
        this.entity = entity;
    }

    public void setMails(List<String> mails) {
        this.mails = mails;
    }

    public void setPhoneNumbers(List<String> phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
    }

}
