package fr.univrouen.stb23v1.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlTransient;

import java.util.ArrayList;
import java.util.List;

/**
 * An STB Feature list.
 */
@Entity
@Table(name = "features")
@XmlAccessorType(XmlAccessType.FIELD)
public class Features {

    /**
     * Autogenerated id.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlTransient
    private Integer id = 1;

    /**
     * The features list.
     */
    @XmlElement
    @OneToMany(targetEntity = Feature.class, cascade = CascadeType.ALL)
    private List<Feature> feature = new ArrayList<>();

    public Features() {
    }

    public Integer getId() {
        return id;
    }

    public List<Feature> getFeature() {
        return feature;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setFeature(List<Feature> feature) {
        this.feature = feature;
    }

}
