package fr.univrouen.stb23v1.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.*;

import java.io.Serializable;

@Entity
@Table(name = "stb")
@XmlRootElement(name = "stb", namespace = "http://univrouen.fr/stb23")
@XmlAccessorType(XmlAccessType.FIELD)
public class STB {

    /**
     * Autogenerated id.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlTransient
    private Integer id;

    /**
     * The STB title.
     */
    @XmlElement
    private String title;

    /**
     * The STB version.
     */
    @XmlElement
    private Double version;

    /**
     * The STB validation date.
     */
    @XmlElement
    private String date;

    /**
     * The STB description.
     */
    @XmlElement
    private String description;

    /**
     * The STB client.
     */
    @XmlElement
    @OneToOne(cascade=CascadeType.ALL)
    @JoinColumn(name = "clientId")
    private Client client;

    /**
     * The STB team.
     */
    @XmlElement
    @OneToOne(cascade=CascadeType.ALL)
    @JoinColumn(name = "teamId")
    private Team team;

    /**
     * The STB features.
     */
    @XmlElement
    @OneToOne(cascade=CascadeType.ALL)
    @JoinColumn(name = "featuresId")
    private Features features;

    public STB() {

    }

    public Integer getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public Double getVersion() {
        return version;
    }

    public String getDate() {
        return date;
    }

    public String getDescription() {
        return description;
    }

    public Client getClient() {
        return client;
    }

    public Team getTeam() {
        return team;
    }

    public Features getFeatures() {
        return features;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setVersion(Double version) {
        this.version = version;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public void setTeam(Team team) {
        this.team = team;
    }

    public void setFeatures(Features features) {
        this.features = features;
    }

}
